// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:whattosolve/env/env.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: Env.firebaseWebApikey,
    appId: Env.firebaseWebAppid,
    messagingSenderId: Env.firebaseMessagingSenderid,
    projectId: 'what-to-solve',
    authDomain: 'what-to-solve.firebaseapp.com',
    databaseURL: Env.firebaseDatabaseUrl,
    storageBucket: 'what-to-solve.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: Env.firebaseAndroidApikey,
    appId: Env.firebaseAndroidAppid,
    messagingSenderId: Env.firebaseMessagingSenderid,
    projectId: 'what-to-solve',
    databaseURL: Env.firebaseDatabaseUrl,
    storageBucket: 'what-to-solve.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: Env.firebaseIosApikey,
    appId: Env.firebaseIosAppid,
    messagingSenderId: Env.firebaseMessagingSenderid,
    projectId: 'what-to-solve',
    databaseURL: Env.firebaseDatabaseUrl,
    storageBucket: 'what-to-solve.appspot.com',
    iosClientId: Env.firebaseIosClientid,
    iosBundleId: 'com.example.recommend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: Env.firebaseMacApikey,
    appId: Env.firebaseMacAppid,
    messagingSenderId: Env.firebaseMessagingSenderid,
    projectId: 'what-to-solve',
    databaseURL: Env.firebaseDatabaseUrl,
    storageBucket: 'what-to-solve.appspot.com',
    iosClientId: Env.firebaseMacClientid,
    iosBundleId: 'com.example.recommend.RunnerTests',
  );
}
